    <div class="coaching">
        <h1><i class="fas fa-dumbbell"></i> Vos Coachings</h1>

        <table id="mytable" class="table table-bordred table-striped table-hover">
                   
            <thead>
                <th scope="col">#</th>
                <th scope="col">Nom</th>
                <th scope="col">Prénom</th>
                <th scope="col">Inscription envoyé le</th>
                <th scope="col">Read</th>
                <th scope="col">Delete</th>
            </thead>
            <tbody>

                <tr>
                    <td scope="row">
                             
                    </td>
                    <td>
                        <a href="<?= $requestUrl ?>/Admin/Onemessage?id=1"><i class="fab fa-readme"></i></a>
                    </td>
                    <td>
                        <button data-id="" class="btn-delete"><i class="fas fa-trash-alt"></i></button>
                    </td>
                </tr>

            </tbody>
        </table>
        <a href="<?= $requestUrl ?>/Admin">Retour à la page admin</a>
    </div>