	<section class="presentation">
		<div>
			<h1>Qui suis-je ?</h1>
			<p>
				Bonjour et bienvenue sur mon site je m'appelle <strong>Dayan Nguyen</strong> et je suis passionné par le sport depuis mon plus jeune âge, j'ai toujours aimé bouger, faire du vélo, crapahuter... C'est ainsi qu'à 5 ans, j'ai commencé le football en club...pour ne plus jamais le quitter.
				J'ai donc naturellement suivi un cursus dans le domaine du sport en Licence STAPS, option Education-Motricité.
				Coach sportif depuis maintenant 2 ans, mon expérience vous permet d'atteindre vos objectifs le plus rapidement possible tout en alliant <strong>bonne humeur, bien être et plaisir</strong>.
			<p>
		</div>
		<div>
			<img src="<?= $wwwUrl ?>/images/personaltrainer.jpg" alt="personal trainer">
		</div>

		
	</section>