	<div class="register">	
		<h1>Register</h1>
		<form action="" method="POST"  id="contact_form">
		    <?php if ( isset($errorMessage) ) : ?>
                <div class="alert alert-danger" role="alert"><?= $errorMessage; ?> *</div>
            <?php endif; ?>
			<?php if ( isset($successMessage) ) : ?>
                <div class="alert alert-success" role="alert"><?= $successMessage; ?> *</div>
            <?php endif; ?>
			<div class="form-group">
				<input name="lastname" type="text" class="form-control" placeholder="Nom" required>
				<div class="hide-alert alert alert-danger" role="alert">Veuillez saissir un nom *</div>
			</div>
			<div class="form-group">
				<input name="firstname" type="text" class="form-control" placeholder="Prénom" required>
				<div class="hide-alert alert alert-danger" role="alert">Veuillez saissir un prénom *</div>
			</div>
			<div class="form-group">
				<input name="email" type="text" class="form-control" placeholder="E-mail" required>
				<div class="hide-alert alert alert-danger" role="alert">Veuillez saissir un Email *</div>
			</div>
			<div class="form-group">
				<input name="password" type="password" class="form-control" id="password" placeholder="Password" required>
				<div class="hide-alert alert alert-danger" role="alert">Veuillez saissir un mot de passe *</div>
			</div>
			<div class="form-group">
				<input name="password_confirm" type="password" class="form-control" id="password_confirm" placeholder="Confirm Password" required>
				<div class="hide-alert alert alert-danger" role="alert">Veuillez saissir un mot de passe *</div>
			</div>
			<div class="form-group">
				<input type="submit" value="S'enregistrer" class="btn btn-primary btn-md btn-lg" name="submit">
			</div>
		</form>
	</div>