	<section class="contact row">
		<div class="col-xl-4 col-lg-5">
			<h2>Suivez-moi</h2>
			<ul class="social">
				<li>
					<a href="https://www.facebook.com/" target="_blank"><i class="fab fa-facebook-f"></i> <span>Facebook</span></a>
				</li>
				<li>
					<a href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram"></i> <span>Instagram</span></a>
				</li>
			</ul>
			<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d10842.774496022368!2d-1.5427725!3d47.2030089!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb740f3e9c4082274!2sBasic-Fit+Salles+de+Sport+Nantes+rue+Anatole+de+Monzie!5e0!3m2!1sfr!2sfr!4v1530811679913" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
		</div>
		  <form action="" method="POST"  id="contact_form" class="col-xl-8 col-lg-7">
            <?php if ( isset($errorMessage) ) : ?>
                <div class="alert alert-danger" role="alert"><?= $errorMessage; ?> *</div>
            <?php endif; ?>
            <div class="form-group">
                <input id="lastname" name="lastname" type="text" class="form-control" placeholder="Nom" required>
                <div class="hide-alert alert alert-danger" role="alert">Veuillez saissir un nom *</div>
            </div>
            <div class="form-group">
                <input id="firstname" name="firstname" type="text" class="form-control" placeholder="Prénom" required>
                <div class="hide-alert alert alert-danger" role="alert">Veuillez saissir un prénom *</div>
            </div>
            <div class="form-group">
                <input id="email" name="email" type="text" class="form-control" placeholder="E-mail" required>
                <div class="hide-alert alert alert-danger" role="alert">Veuillez saissir un E-mail *</div>
            </div>
            <div class="form-group">
                <textarea class="form-control" name="message" id="textarea" cols="30" rows="10" placeholder="Message" required></textarea>
                <div class="hide-alert alert alert-danger" role="alert">Veuillez saissir un message *</div>
            </div>
            <?php if ( isset($successMessage) ) : ?>
                <div class="alert alert-success" role="alert"><?= $successMessage; ?> *</div>
            <?php endif; ?>
            <div class="form-group">
                <input type="submit" value="Envoyer" class="btn btn-primary btn-md btn-lg" name="submit">
            </div>
        </form>

		
	</section>
	