	<div class="login">	

		<h1>Login</h1>

		<small>(Cet espace est réservé à l'administrateur du site)</small>

		<form action="" method="POST"  id="contact_form">
            <div class="form-group">
                <input id="email" name="email" type="text" class="form-control" placeholder="E-mail">
                <div class="hide-alert alert alert-danger" role="alert">Veuillez saissir un E-mail *</div>
            </div>
			 <div class="form-group">
                <input id="password" name="password" type="password" class="form-control" placeholder="password">
                <div class="hide-alert alert alert-danger" role="alert">Veuillez saissir un mot de passe *</div>
            </div>
			<div class="form-group">
				<input type="submit" value="Se connecter" class="btn btn-primary btn-md btn-lg" name="submit">
			</div>
		</form>
	</div>
	